DROP DATABASE IF EXISTS top_songsdb;
CREATE DATABASE top_songsdb;
USE top_songsdb;

CREATE TABLE TOP5000 (
id INT NOT NULL AUTO_INCREMENT, 
artist VARCHAR(40) NOT NULL,
song_name VARCHAR(50) NOT NULL,
release_year INT(4) NOT NULL,
popScoreWorld DECIMAL(10, 4) NOT NULL,
popScoreUSA DECIMAL(10, 4) NOT NULL,
popScoreUK DECIMAL(10, 4) NOT NULL,
popScoreEU DECIMAL(10, 4) NOT NULL,
popScoreROW	DECIMAL(10, 4) NOT NULL,
PRIMARY KEY (id)
);

